# Generated by Django 5.0.4 on 2024-05-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Studio_owner', 'Studio_owner'), ('Studio_owner', 'Studio_owner')], max_length=20),
        ),
    ]
