# Generated by Django 5.0.6 on 2024-05-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Studio_owner', 'Studio_owner'), ('Customer', 'Customer')], max_length=20),
        ),
    ]
